// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {database} from '../models';

export function CategorizeTransaction(arg1:number,arg2:string):Promise<main.CategorizeResult>;

export function CreateAccount(arg1:string):Promise<number>;

export function CreateManualBackup():Promise<string>;

export function CreateOwner(arg1:string):Promise<number>;

export function DeleteCategorizationRule(arg1:number,arg2:boolean):Promise<main.RuleDeleteResult>;

export function DeleteColumnMapping(arg1:number):Promise<void>;

export function DeleteTransactions(arg1:Array<number>):Promise<number>;

export function ExportTransactions(arg1:string,arg2:string,arg3:Array<number>,arg4:Array<number>,arg5:string,arg6:string):Promise<number>;

export function ExportTransactionsWithDialog(arg1:string,arg2:string,arg3:Array<number>,arg4:Array<number>,arg5:string):Promise<number>;

export function FuzzySearch(arg1:string,arg2:Array<string>):Promise<Array<string>>;

export function GetAccounts():Promise<Array<string>>;

export function GetAllUsers():Promise<Array<database.User>>;

export function GetAnalysisTransactions(arg1:string,arg2:string,arg3:Array<number>,arg4:Array<number>):Promise<Array<database.TransactionModel>>;

export function GetAnalysisView(arg1:string,arg2:string,arg3:Array<number>,arg4:Array<number>):Promise<database.AnalysisView>;

export function GetCategories():Promise<Array<database.Category>>;

export function GetCategorizationRules():Promise<Array<database.CategorizationRule>>;

export function GetCategorizationRulesCount():Promise<number>;

export function GetColumnMappings():Promise<Array<database.ColumnMappingModel>>;

export function GetCurrencySettings():Promise<database.CurrencySettings>;

export function GetFxRate(arg1:string,arg2:string,arg3:string):Promise<database.FxRateLookup>;

export function GetFxRateStatus():Promise<database.FxRateStatus>;

export function GetLastBackupInfo():Promise<Record<string, any>>;

export function GetMonthList():Promise<Array<string>>;

export function GetOwners():Promise<Array<string>>;

export function GetRuleAmountRange(arg1:string,arg2:string):Promise<database.AmountRange>;

export function GetRuleMatchCount(arg1:number):Promise<number>;

export function GetUncategorizedTransactions():Promise<Array<database.TransactionModel>>;

export function GetVersion():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ImportTransactions(arg1:Array<main.TransactionInput>):Promise<void>;

export function IsTestEnv():Promise<boolean>;

export function OpenBackupFolder():Promise<string>;

export function ParseExcel(arg1:string):Promise<main.ExcelData>;

export function PreviewRuleMatches(arg1:string,arg2:string,arg3:any,arg4:any):Promise<database.RuleMatchPreview>;

export function RenameCategory(arg1:number,arg2:string):Promise<void>;

export function RestoreBackup(arg1:string):Promise<void>;

export function RestoreBackupFromDialog():Promise<string>;

export function SaveCategorizationRule(arg1:database.CategorizationRule):Promise<main.RuleResult>;

export function SaveColumnMapping(arg1:string,arg2:any):Promise<number>;

export function SearchCategories(arg1:string):Promise<Array<database.Category>>;

export function SearchTransactions(arg1:string,arg2:string,arg3:any,arg4:any):Promise<Array<database.TransactionModel>>;

export function SearchWeb(arg1:string):Promise<Array<main.WebSearchResult>>;

export function SelectBackupFile():Promise<database.BackupMetadata>;

export function SetTestDialogPaths(arg1:main.TestDialogPaths):Promise<void>;

export function ShowAbout():Promise<void>;

export function SyncFxRates():Promise<void>;

export function SyncFxRatesNow():Promise<void>;

export function TriggerAutoBackup():Promise<string>;

export function UndoCategorizationRule(arg1:number,arg2:Array<number>):Promise<void>;

export function UpdateCategorizationRule(arg1:database.CategorizationRule,arg2:boolean):Promise<main.RuleUpdateResult>;

export function UpdateCurrencySettings(arg1:database.CurrencySettings):Promise<database.CurrencySettings>;

export function ValidateBackupFile(arg1:string):Promise<database.BackupMetadata>;
