// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {main} from '../models';

export function DeleteColumnMapping(arg1:number):Promise<void>;

export function GetColumnMappings():Promise<Array<database.ColumnMappingModel>>;

export function Greet(arg1:string):Promise<string>;

export function ImportTransactions(arg1:Array<main.TransactionInput>):Promise<void>;

export function SaveColumnMapping(arg1:string,arg2:any):Promise<number>;
