// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {main} from '../models';

export function CategorizeTransaction(arg1:number,arg2:string):Promise<void>;

export function CreateAccount(arg1:string):Promise<number>;

export function CreateOwner(arg1:string):Promise<number>;

export function DeleteColumnMapping(arg1:number):Promise<void>;

export function GetAccounts():Promise<Array<string>>;

export function GetAnalysisTransactions(arg1:string,arg2:string,arg3:Array<number>):Promise<Array<database.TransactionModel>>;

export function GetCategories():Promise<Array<database.Category>>;

export function GetCategorizationRulesCount():Promise<number>;

export function GetColumnMappings():Promise<Array<database.ColumnMappingModel>>;

export function GetMonthList():Promise<Array<string>>;

export function GetOwners():Promise<Array<string>>;

export function GetUncategorizedTransactions():Promise<Array<database.TransactionModel>>;

export function Greet(arg1:string):Promise<string>;

export function ImportTransactions(arg1:Array<main.TransactionInput>):Promise<void>;

export function ParseExcel(arg1:string):Promise<main.ExcelData>;

export function RenameCategory(arg1:number,arg2:string):Promise<void>;

export function SaveCategorizationRule(arg1:database.CategorizationRule):Promise<number>;

export function SaveColumnMapping(arg1:string,arg2:any):Promise<number>;

export function SearchCategories(arg1:string):Promise<Array<database.Category>>;

export function SearchTransactions(arg1:string,arg2:string,arg3:any,arg4:any):Promise<Array<database.TransactionModel>>;
