// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CategorizeTransaction(arg1, arg2) {
  return window['go']['main']['App']['CategorizeTransaction'](arg1, arg2);
}

export function CreateAccount(arg1) {
  return window['go']['main']['App']['CreateAccount'](arg1);
}

export function CreateManualBackup() {
  return window['go']['main']['App']['CreateManualBackup']();
}

export function CreateOwner(arg1) {
  return window['go']['main']['App']['CreateOwner'](arg1);
}

export function DeleteColumnMapping(arg1) {
  return window['go']['main']['App']['DeleteColumnMapping'](arg1);
}

export function ExportTransactions(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ExportTransactions'](arg1, arg2, arg3, arg4, arg5);
}

export function ExportTransactionsWithDialog(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExportTransactionsWithDialog'](arg1, arg2, arg3, arg4);
}

export function FuzzySearch(arg1, arg2) {
  return window['go']['main']['App']['FuzzySearch'](arg1, arg2);
}

export function GetAccounts() {
  return window['go']['main']['App']['GetAccounts']();
}

export function GetAnalysisTransactions(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetAnalysisTransactions'](arg1, arg2, arg3);
}

export function GetCategories() {
  return window['go']['main']['App']['GetCategories']();
}

export function GetCategorizationRulesCount() {
  return window['go']['main']['App']['GetCategorizationRulesCount']();
}

export function GetColumnMappings() {
  return window['go']['main']['App']['GetColumnMappings']();
}

export function GetCurrencySettings() {
  return window['go']['main']['App']['GetCurrencySettings']();
}

export function GetFxRate(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetFxRate'](arg1, arg2, arg3);
}

export function GetFxRateStatus() {
  return window['go']['main']['App']['GetFxRateStatus']();
}

export function GetLastBackupInfo() {
  return window['go']['main']['App']['GetLastBackupInfo']();
}

export function GetMonthList() {
  return window['go']['main']['App']['GetMonthList']();
}

export function GetOwners() {
  return window['go']['main']['App']['GetOwners']();
}

export function GetUncategorizedTransactions() {
  return window['go']['main']['App']['GetUncategorizedTransactions']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportTransactions(arg1) {
  return window['go']['main']['App']['ImportTransactions'](arg1);
}

export function OpenBackupFolder() {
  return window['go']['main']['App']['OpenBackupFolder']();
}

export function ParseExcel(arg1) {
  return window['go']['main']['App']['ParseExcel'](arg1);
}

export function RenameCategory(arg1, arg2) {
  return window['go']['main']['App']['RenameCategory'](arg1, arg2);
}

export function RestoreBackup(arg1) {
  return window['go']['main']['App']['RestoreBackup'](arg1);
}

export function RestoreBackupFromDialog() {
  return window['go']['main']['App']['RestoreBackupFromDialog']();
}

export function SaveCategorizationRule(arg1) {
  return window['go']['main']['App']['SaveCategorizationRule'](arg1);
}

export function SaveColumnMapping(arg1, arg2) {
  return window['go']['main']['App']['SaveColumnMapping'](arg1, arg2);
}

export function SearchCategories(arg1) {
  return window['go']['main']['App']['SearchCategories'](arg1);
}

export function SearchTransactions(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SearchTransactions'](arg1, arg2, arg3, arg4);
}

export function SearchWeb(arg1) {
  return window['go']['main']['App']['SearchWeb'](arg1);
}

export function SelectBackupFile() {
  return window['go']['main']['App']['SelectBackupFile']();
}

export function ShowAbout() {
  return window['go']['main']['App']['ShowAbout']();
}

export function SyncFxRates() {
  return window['go']['main']['App']['SyncFxRates']();
}

export function TriggerAutoBackup() {
  return window['go']['main']['App']['TriggerAutoBackup']();
}

export function UndoCategorizationRule(arg1, arg2) {
  return window['go']['main']['App']['UndoCategorizationRule'](arg1, arg2);
}

export function UpdateCurrencySettings(arg1) {
  return window['go']['main']['App']['UpdateCurrencySettings'](arg1);
}

export function ValidateBackupFile(arg1) {
  return window['go']['main']['App']['ValidateBackupFile'](arg1);
}
