// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CategorizeTransaction(arg1, arg2) {
  return window['go']['main']['App']['CategorizeTransaction'](arg1, arg2);
}

export function CreateAccount(arg1) {
  return window['go']['main']['App']['CreateAccount'](arg1);
}

export function CreateOwner(arg1) {
  return window['go']['main']['App']['CreateOwner'](arg1);
}

export function DeleteColumnMapping(arg1) {
  return window['go']['main']['App']['DeleteColumnMapping'](arg1);
}

export function FuzzySearch(arg1, arg2) {
  return window['go']['main']['App']['FuzzySearch'](arg1, arg2);
}

export function GetAccounts() {
  return window['go']['main']['App']['GetAccounts']();
}

export function GetAnalysisTransactions(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetAnalysisTransactions'](arg1, arg2, arg3);
}

export function GetCategories() {
  return window['go']['main']['App']['GetCategories']();
}

export function GetCategorizationRulesCount() {
  return window['go']['main']['App']['GetCategorizationRulesCount']();
}

export function GetColumnMappings() {
  return window['go']['main']['App']['GetColumnMappings']();
}

export function GetMonthList() {
  return window['go']['main']['App']['GetMonthList']();
}

export function GetOwners() {
  return window['go']['main']['App']['GetOwners']();
}

export function GetUncategorizedTransactions() {
  return window['go']['main']['App']['GetUncategorizedTransactions']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportTransactions(arg1) {
  return window['go']['main']['App']['ImportTransactions'](arg1);
}

export function ParseExcel(arg1) {
  return window['go']['main']['App']['ParseExcel'](arg1);
}

export function RenameCategory(arg1, arg2) {
  return window['go']['main']['App']['RenameCategory'](arg1, arg2);
}

export function SaveCategorizationRule(arg1) {
  return window['go']['main']['App']['SaveCategorizationRule'](arg1);
}

export function SaveColumnMapping(arg1, arg2) {
  return window['go']['main']['App']['SaveColumnMapping'](arg1, arg2);
}

export function SearchCategories(arg1) {
  return window['go']['main']['App']['SearchCategories'](arg1);
}

export function SearchTransactions(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SearchTransactions'](arg1, arg2, arg3, arg4);
}

export function SearchWeb(arg1) {
  return window['go']['main']['App']['SearchWeb'](arg1);
}
